version: "3.9"

services:
    lambda_name:
        build:
            context: ./
            dockerfile: lambda.dockerfile
        ports: 
            - "9000:8080"
        env_file:
            - .env
     